### ISSUE TITLE
Fresh user review feedback

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-beanvalidation#14]
The guide is very straight forward and effective in terms of leading a new user through the topic.
I can follow each step in the guide without problem, and I was able to implement the application successfully.
The only thing I was not sure about is `@Past` feature introduced in the What's new in Bean Validation 2.0.
Since I'm not very familiar with features from Open Liberty, I'm not sure what `@Past` does.
It is not explained or demonstrated in this guide.
`@Negative` also only got mentioned once, but I could guess its functionality to be the opposite of `@Positive`.
Maybe `@Past` is not related to this guide, but it would be nice if there is a reference to it.
"View this guide on GitHub" in the "Contribute to this guide" section does not work yet, but it's probably because of the naming.
Also, maybe "Injecting dependencies into microserveices" can be added to the "Related guides" section since it was mentioned in the guide.
Overall it is a good guide; it is easy to follow and fun to learn. This guide served its purpose.

**Comment by alexsm82** [comment]
@evelinec I've addressed the comments in the above comment.

**Comment by evelinec** [comment]
@alexsm82 Thank you. I had requested review on the PR #15 . It's good. Thanks.
